### ISSUE TITLE
error in step --dodriz2

### ISSUE THREAD

**Issue by oconnorb** [srodney/sndrizpipe#9]
Hi,

I have been having an error in the --dodriz2 step (all other steps run fine) where $iref is undefined. In the HST handbooks I identified that iref is the directory location for the reference file used in updateWCS for WFC3 IR (and jref for ACS). I am encountering this error when using the colfax test data (and other data, but that is the example I use to demonstrate this error -- see attached).  I have been unable to resolve this error since the pipeline first installed correctly.  Is it possible this is due to some changes made in the new installation where it now runs from command line? I will note that I had a colleague try to reproduce this error following the same steps and they were unable to although they did have the same error with --dotest (shown below).

What led me to think this was that when I try to run the --dotest step:

sndrizpipe --filters "F160w" --ra 189.156538   --dec 62.309147 --mjdmin 56010 --mjdmax 56300 colfax --dotest

I find an error (shown below) where it cannot find the testpipe.py file which is located in sndrizpipe/sndrizpipe directory:

Traceback (most recent call last):
  File "/anaconda2/envs/astroconda/bin/sndrizpipe", line 11, in <module>
    load_entry_point('sndrizpipe==1.0.dev140', 'console_scripts', 'sndrizpipe')()
  File "/anaconda2/envs/astroconda/lib/python3.6/site-packages/sndrizpipe-1.0.dev140-py3.6.egg/sndrizpipe/runpipe_cmdline.py", line 1166, in main
    import testpipe
ModuleNotFoundError: No module named 'testpipe'

I have also attached the errors at step --dodriz2. Please let me know if you can help! I very much appreciate it!

[colfax_f160w_e00_reg_astrodriz.log](https://github.com/srodney/sndrizpipe/files/3769017/colfax_f160w_e00_reg_astrodriz.log)
<img width="750" alt="sndrizpipe_--dodriz2_error" src="https://user-images.githubusercontent.com/56123351/67515959-b6c8ec80-f66d-11e9-9390-fdb0587d99c8.png">

**Comment by srodney** [comment]
Apologies for the slow response.   First, regarding the iref issue, that should be an easy fix.  For some of the DrizzlePac tools to run, you need to have a directory where reference files are kept.   I'm not sure if this actually gets populated with reference files these days (it once did).  I think if you are running from FLT files (i.e. not from raw files) then the directory does not actually need to contain any ref files, and may not even need to exist.  

  Regardless, here is the missing info: 

You must set up some environment variables before running sndrizpipe, using either setenv or export or the equivalent (depending on your shell type).    Here is an example of how I've set this up in my .zshrc file: 

```
# ============================================================
#  IRAF cdbs directories : 

export CDBS=$HOME/Dropbox/cdbs/
export iref=$CDBS/iref/
export jref=$CDBS/jref/
export mtab=$CDBS/mtab/
export cracscomp=$CDBS/comp/acs/
export crotacomp=$CDBS/comp/ota/
export crwfc3comp=$CDBS/comp/wfc3/
export crnicmoscomp=$CDBS/comp/nicmos/
export crrefer=$CDBS/
export PYSYN_CDBS=$CDBS/
```

**Comment by srodney** [comment]
I've pushed a fix for the testpipe script.   I tested it locally, and it works for me, but please let me know if it doesn't succeed for you.

**Comment by oconnorb** [comment]
Thank you very much! All seems to be executing properly now. I really appreciate the help.
